Supplier.Portal/Controllers/AngularController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Supplier.Portal.EntityServices;

namespace Supplier.Portal.Controllers
{
    public class AngularController : Controller
    {
        private OrderShipping _orderShipping;

        // GET: Angular
        public async Task<ViewResult> Index()
        {
            //_orderShipping = new OrderShipping();

            //Tested: LabelRecovery
            //string orderNumber = "";
            //string _imageType = UpsConstants.TestTrackingNumber_Pdf;
            //LabelResponseContainer labelResponseData = new LabelResponseContainer();
            //bool result = _orderShipping.DownloadShippingLabels(orderNumber, _imageType, out labelResponseData);


            //Tested: Void Shipment
            //string shipmentIdNumber = UpsConstants.ShipmentIdNumber;
            //string transactionReference = "TDL Ltd";
            //_orderShipping.CancelShipment(shipmentIdNumber, transactionReference);


            //Tested: 
            //string orderNumber = UpsConstants.TestTrackingNumber_Html;         
            //UpsResponse.PrimaryErrorCode errorData2 = new UpsResponse.PrimaryErrorCode();
            //_orderShipping.ShipOrder(orderNumber, out errorData2);

            return View();
        }
        
        //public ActionResult Settings()
        //{
        //    var settings = new SettingsDto
        //    {
        //        WebHostName = string.Format("{0}/{1}", Request.UrlReferrer != null ? Request.UrlReferrer.AbsoluteUri : "", "api")
        //    };

        //    var serializerSettings = new JsonSerializerSettings
        //    {
        //        ContractResolver = new CamelCasePropertyNamesContractResolver()
        //    };

        //    string settingsJson = JsonConvert.SerializeObject(settings, Formatting.Indented, serializerSettings);

        //    var settingsViewModel = new SettingsViewModel
        //    {
        //        SettingsJson = settingsJson,
        //        AngularModuleName = "app.settings"
        //    };

        //    Response.ContentType = "text/javascript";

        //    return View(settingsViewModel);
        //}   
    }
}

Supplier.Portal/Controllers/UserController.cs
using System.Linq;
using System.Web.Mvc;
using Supplier.Portal.EntityServices;
using Supplier.Portal.ViewModels.User;

namespace Supplier.Portal.Controllers
{
    public class UserController : Controller
    {
        private User _user;

        public UserController()
        {
            _user = new User();
        }

        public ViewResult Users()
        {
            var users = _user.All();

            return View(users.AsEnumerable());
        }
        
        public ActionResult Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                LoggedInUserViewModel userDetails = new LoggedInUserViewModel();

                bool validUser = _user.Login(model, ref userDetails);

                if (validUser)
                {
                    return View("UserInfo", userDetails);
                }

                ModelState.AddModelError("Login", "Invalid Username or Password");
                return View("Login");
            }
            

            return View("Login");
        }

        public ViewResult Register()
        {
            return View();          
        }
    }
}

Supplier.Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Walker Greenbank Supplier Portal</title>
    @Styles.Render("~/bootstrapStyles/css")
    @Styles.Render("~/Site/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .divider-vertical {
            height:1.5em;
            margin: 1em .5em;
            border-left: .5px solid gray;
            border-right: 1px solid silver;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header col-sm-12">
                <a href="/" class="navbar-brand navbar-logo">

                    <span class="brand-title">Walker Greenbank</span>
                </a>
                <a class="btn navbar-btn navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>

                <div class="navbar-collapse collapse col-sm-9 pull-right">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("View in Angular", "Index", "Angular")</li>
                        <li role="presentation" class="divider-vertical"></li>
                        <li>@Html.ActionLink("Login", "Login", "User")</li>
                        <li role="presentation" class="divider-vertical"></li>
                        <li>@Html.ActionLink("Register", "Register", "User")</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        @RenderBody()
        
        <hr />
        @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>