Supplier.Portal/Controllers/CompanyController.cs
using System.Web.Mvc;
using Supplier.Portal.EntityServices;

namespace Supplier.Portal.Controllers
{
    public class CompanyController : Controller
    {
        private Company _company;

        public CompanyController()
        {
            _company = new Company();
        }

        // GET: Company
        public ActionResult Index()
        {
            var companies = _company.All();

            return View(companies);
        }
    }
}

Supplier.Portal/Controllers/HomeController.cs
using System.Web.Mvc;
using Supplier.Portal.DAL;
using Supplier.Portal.DAL.WebEntities;
using Supplier.Portal.Services;

namespace Supplier.Portal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Supplier.Portal/Controllers/RoleController.cs
using System.Web.Mvc;
using Supplier.Portal.EntityServices;

namespace Supplier.Portal.Controllers
{
    public class RoleController : Controller
    {
        private Role _role;

        public RoleController()
        {
            _role = new Role();
        }

        // GET: Role
        public ActionResult Index()
        {
            var roles = _role.All();

            return View(roles);
        }

        // GET: Role/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        // GET: Role/Create
        //public ActionResult Create()
        //{          
        //   return View();
        //}

        // POST: Role/Create
        //[HttpPost]
        //public ActionResult Create(FormCollection collection)
        //{
        //    try
        //    {
        //        RoleViewModel roleModel = new RoleViewModel { Name = "SupplierAdmin" };
        //        _role.Add(roleModel);
               

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: Role/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        // POST: Role/Edit/5
        //[HttpPost]
        //public ActionResult Edit(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add update logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: Role/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        // POST: Role/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

Supplier.Portal/Controllers/UserController.cs
using System.Linq;
using System.Web.Mvc;
using Supplier.Portal.EntityServices;
using Supplier.Portal.ViewModels.User;

namespace Supplier.Portal.Controllers
{
    public class UserController : Controller
    {
        private User _user;

        public UserController()
        {
            _user = new User();
        }

        public ViewResult Users()
        {
            var users = _user.All();

            return View(users.AsEnumerable());
        }
        
        public ActionResult Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                LoggedInUserViewModel userDetails = new LoggedInUserViewModel();

                bool validUser = _user.Login(model, ref userDetails);

                if (validUser)
                {
                    return View("UserInfo", userDetails);
                }

                ModelState.AddModelError("Login", "Invalid Username or Password");
                return View("Login");
            }
            

            return View("Login");
        }

        public ViewResult Register()
        {
            return View();          
        }
    }
}

Supplier.Portal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Supplier.Portal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Supplier.Portal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@*<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>*@

<h4>Links</h4>

<br/>
<div class="row">
    <div class="col-sm-12">
        @Html.ActionLink("Companies", "Index", "Company")<br/>
        @Html.ActionLink("Roles", "Index", "Role")<br />
        @Html.ActionLink("Users", "Users", "User")<br />
        @Html.ActionLink("Dashboard", "Index", "Dashboard")<br/>
    </div>
</div>